[project]
name = 'Tokenized-Marketing-Influencer-Campaign-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.campaign-coordination]
path = 'contracts/campaign-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.influencer-verification]
path = 'contracts/influencer-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
